//
// Created by horacio on 3/19/17.
//

#ifndef DAKARASERVER_DOTIOCHARINITIALIZER_H
#define DAKARASERVER_DOTIOCHARINITIALIZER_H

void updateInventory(int UserIndex);

#endif //DAKARASERVER_DOTIOCHARINITIALIZER_H
